# Generated by Django 6.0.5 on 2026-06-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=200)),
                ('excursion_type', models.CharField(choices=[('theater_plus', 'Театр+'), ('group_show', 'Групповой спектакль'), ('group_excursion', 'Обычная групповая экскурсия')], max_length=30)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('participants_total', models.PositiveIntegerField(default=0)),
                ('participants_pushkin', models.PositiveIntegerField(default=0)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_bar', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('art', 'Художественная'), ('thematic', 'Тематическая'), ('historical', 'Историческая'), ('other', 'Другая')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('works_count', models.PositiveIntegerField(default=0)),
                ('contact_person', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Активна'), ('completed', 'Завершена')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('broadcast', 'Трансляция'), ('online', 'Онлайн-активность')], max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Онлайн-мероприятие',
                'verbose_name_plural': 'Онлайн-мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Постановка',
                'verbose_name_plural': 'Постановки',
            },
        ),
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_items', to='core.excursion')),
            ],
            options={
                'verbose_name': 'Позиция бара',
                'verbose_name_plural': 'Позиции бара',
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.production'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('excursion', 'Сотрудник отдела экскурсионной деятельности'), ('viewer', 'Сотрудник стороннего отдела')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
