# Generated by Django 6.0.5 on 2026-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трансляция',
                'verbose_name_plural': 'Трансляции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='onlineevent',
            name='event_type',
            field=models.CharField(choices=[('online', 'Онлайн-активность')], max_length=20),
        ),
    ]
